# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38f105010dbe1e273f2f0504ea2d41830c5e0ed641ca5198f321c18f4453986d842741c29bca8003cdc4333ece00027473759cc3746d44556599ecdf90b3694b

test:
  secret_key_base: c11747967a920c7f20040fbb8a7761452cca62717329d9d51d75fc9c7cd52f6b2aca15c42c58533371b3af2898af97a3b45deaf37f3a2fc72ead45c8574e6f75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
